# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/p6210/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/samsung/p6210/proprietary/ril/lib/libril.so:obj/lib/libril.so \
    vendor/samsung/p6210/proprietary/ril/lib/libsecril-client.so:obj/lib/libsecril-client.so

# RIL
PRODUCT_COPY_FILES += \
    vendor/samsung/p6210/proprietary/ril/bin/rild:system/bin/rild \
    vendor/samsung/p6210/proprietary/ril/lib/libril.so:system/lib/libril.so \
    vendor/samsung/p6210/proprietary/ril/lib/libsec-ril-apalone.so:system/lib/libsec-ril-apalone.so \
    vendor/samsung/p6210/proprietary/ril/lib/libsecril-client.so:system/lib/libsecril-client.so

# LPM
PRODUCT_COPY_FILES += \
    vendor/samsung/p6210/proprietary/lpm/bin/charging_mode:system/bin/charging_mode \
    vendor/samsung/p6210/proprietary/lpm/bin/immvibed:system/bin/immvibed \
    vendor/samsung/p6210/proprietary/lpm/bin/playlpm:system/bin/playlpm \
    vendor/samsung/p6210/proprietary/lpm/lib/libQmageDecoder.so:system/lib/libQmageDecoder.so \
    vendor/samsung/p6210/proprietary/lpm/media/battery_batteryerror.qmg:system/media/battery_batteryerror.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_batteryerror_180.qmg:system/media/battery_batteryerror_180.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_error.qmg:system/media/battery_error.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_error_180.qmg:system/media/battery_error_180.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_charging_0.qmg:system/media/battery_charging_0.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_charging_0_180.qmg:system/media/battery_charging_0_180.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_charging_100.qmg:system/media/battery_charging_100.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_charging_100_180.qmg:system/media/battery_charging_100_180.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_charging_20.qmg:system/media/battery_charging_20.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_charging_20_180.qmg:system/media/battery_charging_20_180.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_charging_40.qmg:system/media/battery_charging_40.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_charging_40_180.qmg:system/media/battery_charging_40_180.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_charging_60.qmg:system/media/battery_charging_60.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_charging_60_180.qmg:system/media/battery_charging_60_180.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_charging_80.qmg:system/media/battery_charging_80.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/battery_charging_80_180.qmg:system/media/battery_charging_80_180.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/chargingwarning.qmg:system/media/chargingwarning.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/chargingwarning_180.qmg:system/media/chargingwarning_180.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/Disconnected.qmg:system/media/Disconnected.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/Disconnected_180.qmg:system/media/Disconnected_180.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/bootsamsung.qmg:system/media/bootsamsung.qmg \
    vendor/samsung/p6210/proprietary/lpm/media/bootsamsungloop.qmg:system/media/bootsamsungloop.qmg

